[package]
name = "jcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
compact_str.workspace = true
delegate = "0.10.0"
getset = "0.1.2"
strum = "0.25"
strum_macros = "0.25"
