name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: make (All)
      run: make
    - name: make debug (Linux, Mac)
      if: matrix.os != 'windows-latest'
      run: make debug=1
    - name: run release (All)
      run: make run
    - name: run sanitizer (Linux, Mac)
      if: matrix.os != 'windows-latest'
      run: make sanitizer
    - name: run valgrind (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install -y valgrind
        make valgrind
    - name: run leaks (Mac)
      if: matrix.os == 'macos-latest'
      run: |
        make leaks
