[package]
name = "hvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compact_str = "0.7.1"
smallvec = "1.11.1"
strum = "0.25.0"
strum_macros = "0.25"
